language: node_js
node_js:
- '0.10'
before_install:
  - npm install -g npm
  - sudo apt-get install tofrodos
  - sudo ln -s /usr/bin/fromdos /usr/bin/dos2unix
after_success:
  - "./_travis/build.sh"
deploy:
  provider: releases
  api_key:
    secure: DCOkYhsd/rVqKyWS9deaYx+IBd80pz820yOVIDdZgPiBlHX/oOu22rmvDu8nb72UAjol1aenwKwgOEm6sgcsZTwA1IOw1Bwicc7GmHM93LFYoJozcfsXtCFiw7KFFyikuSUibfgJexyEIhnJpSvWrEayzMZK+zuyjoel7AhajZ4=
  file:
    - build/JSer.info-editor-osx.zip
    - build/JSer.info-editor-win.zip
#    - build/JSer.info-editor-linux32.zip
#    - build/JSer.info-editor-linux64.zip
  on:
    repo: jser/jser.info-editor
    tags: true
    all_branches: true
  skip_cleanup: true