sudo: false
language: node_js
node_js: "stable"
before_install:
  - npm install -g npm
after_success:
- test ${TRAVIS_TAG} && npm run dist
deploy:
  provider: releases
  api_key:
    secure: DCOkYhsd/rVqKyWS9deaYx+IBd80pz820yOVIDdZgPiBlHX/oOu22rmvDu8nb72UAjol1aenwKwgOEm6sgcsZTwA1IOw1Bwicc7GmHM93LFYoJozcfsXtCFiw7KFFyikuSUibfgJexyEIhnJpSvWrEayzMZK+zuyjoel7AhajZ4=
  file:
    - build/JSer.info-editor-osx32.zip
    - build/JSer.info-editor-osx64.zip
    - build/JSer.info-editor-win32.zip
    - build/JSer.info-editor-win64.zip
#    - build/JSer.info-editor-linux32.zip
#    - build/JSer.info-editor-linux64.zip
  on:
    repo: jser/jser.info-editor
    tags: true
    all_branches: true
  skip_cleanup: true